#define FALSE 0
#define TRUE 1

#define WINDOW_SCALE 8

#define WINDOW_WIDTH (160 * WINDOW_SCALE)
#define WINDOW_HEIGHT (90 * WINDOW_SCALE)

#define FPS 60
#define FRAME_TARGET_TIME (1000 / FPS)

#define GRID_SPACING 64